import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import Ascii from "../components/ascii/p5";
import TopBar from "@/components/general/topBar";
import "./globals.css";

const inter = Inter_Tight({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TopBar />

                <div className="w-screen h-screen fixed top-0 left-0 z-[-1]">
                    <Ascii flag={0} />
                </div>

                {children}
            </body>
        </html>
    );
}
